import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "IronFit",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <head>
        <link rel="icon" href="/icon.png" />
      </head>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </>
  );
}
